export const TOGGLE_REGISTER_FORM = "TOGGLE_REGISTER_FORM",
  CREATE_USER = "CREATE_USER",
  ADD_USER = "ADD_USER",
  GET_LOGOS = "GET_LOGOS",
  ADD_LOGO_TO_CART = "ADD_LOGO_TO_CART",
  REMOVE_LOGO_FROM_CARD = "REMOVE_LOGO_FROM_CARD",
  RESET_LOGO_STATE = "RESET_LOGO_STATE";
